print('Jawwad 18b-007-CS')
print('Detailed Assignment q25')
L_element = eval(input('Enter a list:'))
print('The first list element is',L_element[0])
print('The last element in list is',L_element[-1])
